<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-COQHVDGR" ignored="7" name="Default test" tests="1" failures="1" timestamp="21 May 2021 03:43:17 GMT" time="0.076" errors="0">
  <testcase name="verifyUrl" time="0.016" classname="com.jbk.test.RegisterTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at com.jbk.test.RegisterTest.verifyUrl(RegisterTest.java:28)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- verifyUrl -->
  <testcase name="verifyAlreadyMemberText" time="0.0" classname="com.jbk.test.RegisterTest">
    <ignored/>
  </testcase> <!-- verifyAlreadyMemberText -->
  <testcase name="verifyAlreadyMemberLink" time="0.0" classname="com.jbk.test.RegisterTest">
    <ignored/>
  </testcase> <!-- verifyAlreadyMemberLink -->
  <testcase name="verifyValidSignIn" time="0.0" classname="com.jbk.test.RegisterTest">
    <ignored/>
  </testcase> <!-- verifyValidSignIn -->
  <testcase name="verifyBlankSignIn" time="0.0" classname="com.jbk.test.RegisterTest">
    <ignored/>
  </testcase> <!-- verifyBlankSignIn -->
  <testcase name="verifyHeading" time="0.0" classname="com.jbk.test.RegisterTest">
    <ignored/>
  </testcase> <!-- verifyHeading -->
  <testcase name="verifyTitle" time="0.0" classname="com.jbk.test.RegisterTest">
    <ignored/>
  </testcase> <!-- verifyTitle -->
  <testcase name="verifyPlaceholders" time="0.0" classname="com.jbk.test.RegisterTest">
    <ignored/>
  </testcase> <!-- verifyPlaceholders -->
</testsuite> <!-- Default test -->
